PixelCMS.Web/Controllers/ContentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PixelCMS.Core.Models;
using PixelCMS.Helpers;
using System.Collections;
using PagedList;
// -----------------------------------------
// PIXEL CMS
// ContentController.cs v4.0
// Feb.2014
// Author: Zhouhai - tuanhai.chau@gmail.com
// Copyright (c) 2014
// -----------------------------------------
namespace PixelCMS.Controllers
{
    public class ContentController : BaseController
    {
        private pixelcmsEntities db = new pixelcmsEntities();
        //
        // GET: /Content/

        public ActionResult Slug(string slug1, string slug2, string slug3, string slug4, string culture, int? page)
        {
            #region BREADCRUMB
            if (slug4 != null)
            {
                ViewBag.BreadCrumb = slug4;
            }
            else if (slug3 != null)
            {
                ViewBag.BreadCrumb = slug3;
            }
            else if (slug2 != null)
            {
                ViewBag.BreadCrumb = slug2;
            }
            else if (slug1 != null)
            {
                ViewBag.BreadCrumb = slug1;
            }
            #endregion

            #region LANGUAGE (CONSTRUCTION)
            var currentlang = db.Languages.FirstOrDefault(x => x.Code == culture);
            if (currentlang.Construction == true)
            {
                return RedirectToAction("UnderConstruction", "Errors");
            }
            else if (currentlang.Active == false)
            {
                return RedirectToRoute("Errors", new { culture = culture });
            }
            #endregion

            #region CONTENT (Posttype, Cat, Post)
            var sluglist1 = db.Slugs.FirstOrDefault(x => x.Slug_Full == slug1 && x.Lang == culture);
            var langposttype = true;
            if (sluglist1 == null)
            {
                sluglist1 = db.Slugs.FirstOrDefault(x => x.Slug_Full == slug1);
                langposttype = false;
            }

            if (sluglist1 != null)
            {
                if (slug2 == null)
                {
                    #region Slug 1
                    if (sluglist1.PostType != null)
                    {
                        #region /news/
                        var posttype = db.PostTypes.Find(sluglist1.PostType);
                        if (posttype.AsPost == false || posttype.Active == false  || langposttype == false)
                        {
                            return RedirectToRoute("Errors", new { culture = culture });
                        }


                        var postculture = "";
                        if (posttype.Has_Parallel_Language == true)
                        {
                            postculture = db.Languages.OrderBy(o => o.Order).FirstOrDefault().Code;
                        }
                        else
                        {
                            postculture = culture;
                        }
                        var posts = posttype.Posts.Where(x => x.Active == true && x.Lang == postculture);
                        if (posttype.Has_Order == true)
                        {
                            posts = posts.OrderByDescending(x => x.Order).ToList();
                        }
                        else
                        {
                            posts = posts.OrderByDescending(o => o.Date_Create).ToList();
                        }
                        int pageSize = 6;
                        int pageNumber = (page ?? 1);
                        ViewBag.TypeName = posttype.PostType_Name.FirstOrDefault(x => x.Lang == culture).Name;

                        ViewBag.PosttypeId = posttype.Id;
                        posts = posts.OrderByDescending(x => x.Order).ThenByDescending(x => x.Date_Create);
                        if (posttype.Code == "product")
                        {
                           pageSize = 6;
                           return View("ProductList", posts.OrderByDescending(x => x.Order).ThenByDescending(x => x.Date_Create).ToPagedList(pageNumber, pageSize));
                           // var cat1 = db.Cats.Where(x => x.Position == 1 && x.Active).OrderByDescending(x => x.Order).ToList();
                           // return View("ProductList1", cat1);
                        }
                        else if (posttype.Code == "project")
                        {
                            return View("ProjectList", posts.ToPagedList(pageNumber, pageSize));
                        }
                        else if (posttype.Code == "slide-doi-tac")
                        {
                            pageSize = 1000;
                            return View("gallery", posts.ToPagedList(pageNumber, pageSize));
                        }
                        else if (posttype.Code == "customer")
                        {
                            return View("CustomerList", posts.ToPagedList(pageNumber, pageSize));
                        }
                        else if (posttype.Code == "photo")
                        {
                            pageSize = 24;
                           // var cat = db.Cats.Where(x => x.PostType.Code=="photo" && x.Active).OrderByDescending(x => x.Order).ToList();
                            return View("PhotoList", posts.ToPagedList(pageNumber, pageSize));
                        }
                        return View("PostList", posts.OrderByDescending(x => x.Order).ThenByDescending(x => x.Date_Create).ToPagedList(pageNumber, pageSize));
                        #endregion
                    }
                    else if (sluglist1.Cat != null)
                    {
                        #region /cat/
                        var cat = db.Cats.Find(sluglist1.Cat);
                        string catid = cat.Id.ToString();
                        cat.RealId = cat.Id;
                        if (cat.PostType.Has_Parallel_Language && cat.MainLang_Id != null)
                        {
                            var cattemp = cat;
                            cat = db.Cats.Find(cattemp.MainLang_Id);
                            cat.Name = cattemp.Name;
                            cat.Lang = cattemp.Lang;
                            cat.RealId = cattemp.Id;
                            catid = cat.Id.ToString();
                        }

                        if (cat == null || cat.Lang != culture || cat.PostType.AsPost == false || cat.Active == false || cat.PostType.Active == false )
                        {
                            return RedirectToRoute("Errors", new { culture = culture });
                        }

                        var posts = db.Posts.Where(x => x.Cats.FirstOrDefault((c => c.Id == cat.Id | c.Parent_Path.Contains(catid))) != null && x.Active == true).ToList();
                        if (cat.PostType.Has_Order == true)
                        {
                            posts = posts.OrderBy(x => x.Order).ToList();
                        }

                        int pageSize = 6;
                        int pageNumber = (page ?? 1);
                        ViewBag.TypeName = cat.Name;
                        ViewBag.CatKey = cat.Meta_Key;
                        ViewBag.CatDescription = cat.Meta_Description;
                        ViewBag.CatHead = cat.Html_Head;
                        ViewBag.CatTitle = cat.Meta_Title;
                        ViewBag.PosttypeId = cat.PostType.Id;

                        if (cat.PostType.Code == "product")
                        {
                            return View("ProductList", posts.OrderByDescending(x => x.Order).ThenByDescending(x => x.Date_Create).ToPagedList(pageNumber, pageSize));
                           // var cat1 = db.Cats.Where(x => x.Position == 1 && x.Active).OrderByDescending(x => x.Order).ToList();
                            //return View("ProductList", cat1);
                        }
                        if (cat.PostType.Code == "project")
                        {
                            pageSize = 500;
                            return View("ProjectList", posts.OrderByDescending(x => x.Order).ThenByDescending(x => x.Date_Create).ToPagedList(pageNumber, pageSize));
                        }
                        return View("PostList", posts.OrderByDescending(x => x.Order).ThenByDescending(x => x.Date_Create).ToPagedList(pageNumber, pageSize));
                        #endregion
                    }
                    else if (sluglist1.Post != null)
                    {
                        #region /post/
                        var post = db.Posts.Find(sluglist1.Post);
                        ViewBag.TypeName = post.PostType.PostType_Name.FirstOrDefault(x => x.Lang == culture).Name;
                        if (post.PostType.Has_Parallel_Language && post.MainLang_Id != null)
                        {
                            var posttemp = post;
                            post = db.Posts.Find(posttemp.MainLang_Id);
                            post.Title = posttemp.Title;
                            post.Description = posttemp.Description;
                            post.Content = posttemp.Content;
                            post.Lang = posttemp.Lang;
                        }

                        if (post == null || post.Lang != culture || post.PostType.AsPost == false || post.Active == false || post.PostType.Active == false )
                        {
                            return RedirectToAction("NotFound", "Errors");
                        }

                        if (post.PostType.Code == "mainpage")
                        {
                            return View("PageDetail", post);
                        }
                        if (post.PostType.Code == "product")
                        {
                            return View("ProductDetail", post);

PixelCMS.Web/Areas/Admin/Views/VariantAttribute/Create.cshtml
@using PixelCMS.Core.Models
@model PixelCMS.Core.Models.VariantAttribute

@{
    ViewBag.Title = "Tạo biến thể";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    pixelcmsEntities db = new pixelcmsEntities();
}
<section id="main">

    <div class="container">
        <div class="sixteen columns">
            <h1>Tạo biến thể</h1>

            @using (Html.BeginForm())
            {
                @Html.HiddenFor(x => x.PostId)
                @Html.ValidationSummary(true)
                <aside id="control">
                    <div>
                        <input type="submit" value="Tạo" class="btn btn-blue" />
                        <a href="@Url.Action("Index", new { postid = Model.PostId })" class="btn"><i class="fa fa-chevron-left"></i>Quay lại</a>
                    </div>
                </aside>
    
                <table class="grid form-input">
                    <tr>
                        <th colspan="2">Thông tin cơ bản</th>
                    </tr>
                   @* <tr>
                        <td class="label">Tên thuộc tính</td>
                        <td>
                            @Html.TextBoxFor(model => model.Name, new { required = true })
                            @Html.ValidationMessageFor(model => model.Name)
                        </td>
                    </tr>*@
                    <tr>
                        <td class="label">
                            Tên nhóm thuộc tính
                             <i title="Nhóm thuộc tính này được tạo sẵn ở menu'Sản phẩm-->Thuộc tính biến thể-->Chọn nhóm thuộc tính'" class="fa fa-question-circle"></i>
                        </td>
                        <td>@Html.DropDownList("VariantGroup_Id")
                            @Html.ValidationMessageFor(model => model.VariantGroup_Id)
                        </td>
                    </tr>
                    <tr>
                        <td class="label">
                            Loại input
                             <i title="Là cách hiển thị của thuộc tính.VD:Ô màu sắc sẽ hiển thị nhìu ô màu sắc." class="fa fa-question-circle"></i>
                        </td>
                        <td>
                            <select name="Type">
                                <option value="0">Chọn</option>
                                <option value="1">Ô màu sắc</option>
                                <option value="2">Ô check(Cho chọn nhiều)</option>
                                <option value="3">Ô tròn radio(Cho chọn 1)</option>
                                 <option value="5">Ô vuông radio(Cho chọn 1 'có css')</option>
                                <option value="4">Danh sách đổ xuống</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="label">kích hoạt</td>
                        <td>
                            @Html.CheckBoxFor(model => model.Active)
                        </td>
                    </tr>
                </table>
            }

        </div>
    </div>

</section>

PixelCMS.Web/Areas/Admin/Views/VariantAttribute/Edit.cshtml
@using PixelCMS.Core.Models
@model PixelCMS.Core.Models.VariantAttribute

@{
    ViewBag.Title = "edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    pixelcmsEntities db = new pixelcmsEntities();
}

<section id="main">

    <div class="container">
        <div class="sixteen columns">
            <h1>Chỉnh sửa biến thể</h1>

            @using (Html.BeginForm())
            {
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.PostId)
                @Html.ValidationSummary(true)
                <aside id="control">
                    <div>
                        <input type="submit" value="Sửa" class="btn btn-blue" />
                       <a href="@Url.Action("Index", new { postid = Model.PostId })" class="btn"><i class="fa fa-chevron-left"></i>Quay lại</a>
                    </div>
                </aside>
    
               <table class="grid form-input">
                    <tr>
                        <th colspan="2">Thông tin cơ bản</th>
                    </tr>
                   @* <tr>
                        <td class="label">Tên thuộc tính</td>
                        <td>
                            @Html.TextBoxFor(model => model.Name, new { required = true })
                            @Html.ValidationMessageFor(model => model.Name)
                        </td>
                    </tr>*@
                    <tr>
                        <td class="label">Tên nhóm thuộc tính</td>
                        <td>@Html.DropDownList("VariantGroup_Id")
                            @Html.ValidationMessageFor(model => model.VariantGroup_Id)
                        </td>
                    </tr>
                    <tr>
                        <td class="label">Loại input</td>
                        <td>
                            @Html.DropDownList("Type")
                        </td>
                    </tr>
                    <tr>
                        <td class="label">kích hoạt</td>
                        <td>
                            @Html.CheckBoxFor(model => model.Active)
                        </td>
                    </tr>
                </table>

            }

        </div>
    </div>

</section>
<script>
    $(function () {
        $("#StartDate").datepicker({
            showOn: "button",
            buttonImage: "/Theme/images/icons/calendar.gif",
            buttonImageOnly: true,
            //dateFormat: 'mm/dd/yy 00:00:00'
        });
    });
    $(function () {
        $("#EndDate").datepicker({
            showOn: "button",
            buttonImage: "/Theme/images/icons/calendar.gif",
            buttonImageOnly: true,
            //  changeMonth: true,
            // changeYear: true,
            //dateFormat: 'mm/dd/yy 00:00:00'
        });
    });
</script>

PixelCMS.Web/Areas/Admin/Views/VariantAttribute/Index.cshtml
@model PagedList.IPagedList<PixelCMS.Core.Models.VariantAttribute>
@using PagedList.Mvc;
@using PixelCMS.Core.Models;
@{
    pixelcmsEntities db = new pixelcmsEntities();
    ViewBag.Title = "Biến thể";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    int postid = ViewBag.postId;
    var post = db.Posts.FirstOrDefault(x => x.Id == postid);
}

<div class="alert alert-info" id="delete-success" style="display: none;">
    <i class="fa fa-exclamation-circle"></i>@Resources.admin_cart_order @Resources.admin_status_deletedsuccessfully
</div>

<div class="alert alert-info" id="edit-success" style="display: none;">
    <i class="fa fa-exclamation-circle"></i>@Resources.admin_common_edit @Resources.admin_cart_order @Resources.admin_status_successfully
</div>

<div class="alert alert-info" id="create-success" style="display: none;">
    <i class="fa fa-exclamation-circle"></i>@Resources.admin_common_create @Resources.admin_cart_order @Resources.admin_status_successfully
</div>

<section id="main">
    <div class="container">
        <div class="head">
            <div class="isw-cloud"></div>
            <h1>Biến thể</h1>

            <div class="clear"></div>
        </div>
        <div class="block-fluid table-sorting" style="float: left; width: 100%;">
            <div class="sixteen columns">
                <aside id="control">
                    <div>
                        <a class="btn btn-blue" href="@Url.Action("Create", new { postid = ViewBag.postId })"><i class="fa fa-plus"></i>@Resources.admin_common_create</a>
                        <a class="btn btn-green" href="@Url.Action("Index", "VariantAttributeCombination", new { postid = ViewBag.postId })">Kết hợp thuộc tính
                         <i title="Quản lý sản phẩm với thuộc tính và số lượng.VD:Ở đây sẽ tạo ra được sp có thuộc tính cụ thể:Size M,Color Xanh.với sp này có mã hàng ,số lượng và giá bán riêng biệt." class="fa fa-question-circle"></i>
                        </a>
                        <a href="@Url.Action("Edit", "Content", new { id = post.Id })" class="btn"><i class="fa fa-chevron-left"></i>Quay lại</a>
                    </div>
                </aside>
                <table class="grid">
                    <tr>
                        <th>Tên biến thể
                        </th>
                        <th>Loại input
                        </th>
                        <th>kích hoạt
                        </th>
                        <th>Danh sách thuộc tính
                        </th>
                        <th width="20%"></th>
                    </tr>
                    @foreach (var item in Model)
                    {<tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.GroupVariant.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TypeText)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Active)
                    </td>
                    <td>
                        <a style="font-weight: bold;text-decoration: underline;color: royalblue" href="@Url.Action("Index", "Variant", new { VariantAtt_Id = item.Id, VariantGroup_Id = item.VariantGroup_Id, PostId = ViewBag.PostId })">Xem danh sách
                             <i title="VD:Color có nhìu màu:xanh,đỏ,vàng tím..." class="fa fa-question-circle"></i>
                        </a>
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-small"><i class="fa fa-pencil-square-o"></i>@Resources.admin_common_edit</a>
                        <a href="@Url.Action("Delete", new { id = item.Id })" class="btn btn-small btn-red delete-link"><i class="fa fa-trash-o"></i>@Resources.admin_content_delete</a>
                    </td>
                </tr>
                   
                    }

                </table>

                <div>
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
                    @Resources.common_viewingpage @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) (@Resources.common_in @Model.PageCount @Resources.admin_common_page)
                </div>
            </div>
        </div>
    </div>
</section>


<div id="delete-dialog" title="@Resources.admin_common_confirm">
    <p>@Resources.admin_ask_suredelete @Resources.admin_cart_order</p>
</div>
<script>
    var deleteLinkObj;
    // delete Link
    $('.delete-link').click(function () {
        deleteLinkObj = $(this);  //for future use
        $('#delete-dialog').dialog('open');
        return false; // prevents the default behaviour
    });
    $('#delete-dialog').dialog({
        autoOpen: false, width: 400, resizable: false, modal: true, //Dialog options
        buttons: {
            "@Resources.admin_content_delete": function () {
                $.post(deleteLinkObj[0].href, function (data) {  //Post to action
                    if (data == '@Boolean.TrueString') {
                        deleteLinkObj.closest("tr").hide('fast'); //Hide Row
                        $("#delete-success:hidden:first").fadeIn("slow").delay(1500).fadeOut("slow");
                        //(optional) Display Confirmation
                    }
                    else {
                        //(optional) Display Error
                    }
                });
                $(this).dialog("close");
            },
            "@Resources.admin_common_back": function () {
                $(this).dialog("close");
            }
        }
    });
</script>