PixelCMS.Web/Controllers/CommonController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Security;
using Microsoft.AspNet.SignalR;
using Newtonsoft.Json;
using PixelCMS.Core.Models;
using PixelCMS.Mailer;
using PixelCMS.Helpers;
using PagedList;

// -----------------------------------------
// PIXEL CMS
// CommonController.cs v1.2
// Feb.2014
// Author: Zhouhai - tuanhai.chau@gmail.com
// Copyright (c) 2014
// -----------------------------------------
namespace PixelCMS.Controllers
{
    public class CommonController : BaseController
    {
        private string currentlang = CultureHelper.GetCurrentNeutralCulture();
        private pixelcmsEntities db = new pixelcmsEntities();
        #region header
        public ActionResult Header()
        {
            return PartialView("_Header");
        }
        #endregion

        #region Menu
        public ActionResult Menu(string culture, string positioncode, string vitri)
        {
            var menus = db.MenuItems.Where(x => x.Menu1.MenuPosition1.Active == true && x.Menu1.MenuPosition1.Code == positioncode && x.Active == true && x.Menu1.Lang == culture).OrderBy(o => o.Order).ToList();
            // Moi position moi thi tao them 1 "if" va tra ve mot view moi
            if (positioncode == "menu-top")
                return PartialView("_MenuTop", menus);

            if (positioncode == "menu-footer" || positioncode == "menu-footer1")
                return PartialView("_Menu_Footer", menus);

            if (positioncode == "menu-left" | positioncode == "menu-award" | positioncode == "menu-invertor")
                return PartialView("_MenuLeft", menus);
            if (vitri == "footer")
                return PartialView("_Menu_Footer", menus);

            return PartialView("_Menu", menus);
        }
        #endregion

        #region Footer
        public ActionResult Footer()
        {
            return PartialView("_Footer");
        }
        #endregion

        #region Left
        /*   public ActionResult MenuLeft(string culture, string positioncode)
        {
            var menus = db.MenuItems.Where(x => x.Menu1.MenuPosition1.Active == true && x.Menu1.MenuPosition1.Code == positioncode && x.Active == true && x.Menu1.Lang == culture).OrderBy(o => o.Order).ToList();

            return PartialView("_MenuLeft", menus);
        }*/

        public ActionResult Left()
        {
            return PartialView("_Left");
        }
        #endregion

        #region Option
        //
        // GET: /Common/
        public string LoadOption(string code)
        {
            try
            {
                Option conf = db.Options.FirstOrDefault(c => c.Code == code);
                conf.Value = System.Web.HttpUtility.HtmlDecode(conf.Value);
                return conf.Value;
            }
            catch
            {
                return string.Empty;
            }
        }
        #endregion

        #region URL
        public string LoadURL(string culture, string type, int id = 0)
        {
            try
            {
                var url = "#";
                if (type == "posttype")
                {
                    var posttype = db.Slugs.FirstOrDefault(x => x.PostType == id && x.Lang == culture).Slug_Full;
                    url = "/" + culture + "/" + posttype;
                }
                else if (type == "post")
                {
                    var post = db.Posts.Find(id);
                    var postslug = db.Slugs.FirstOrDefault(x => x.Post == post.Id).Slug_Full;
                    // Luu y slug culture cua Post va Cat la khac nhau
                    // NEU WEBSITE 1 NGON NGU THI BO CAC PHAN CULTURE VA LANG DI (LUU Y LA VAN GIU LAI PHAN RESOURCE

                    #region POST LINK
                    if (post != null)
                    {
                        if (post.PostType.AsPost == true && post.PostType.Active == true)
                        {
                            //edit by luan
                            url = "/" + post.Lang + "/" + postslug;

                            //old
                            if (post.PostType.ShowType == true)
                            {
                                var posttype = db.Slugs.FirstOrDefault(x => x.PostType == post.PostType.Id && x.Lang == culture).Slug_Full;
                                url = "/" + post.Lang + "/" + posttype + "/" + postslug;
                            }

                        }
                    }
                    #endregion
                }
                else if (type == "cat")
                {
                    var cat = db.Cats.Find(id);
                    //  var posttype = db.Slugs.FirstOrDefault(x => x.PostType == cat.PostType.Id && x.Lang == culture).Slug_Full;
                    var catslug = db.Slugs.FirstOrDefault(x => x.Cat == cat.Id).Slug_Full;
                    if (cat.PostType.Has_Parallel_Language && cat.MainLang_Id != null)
                    {
                        var tmp = db.Cats.Find(cat.MainLang_Id).Owner_Id;
                        if (tmp != null)
                        {
                            cat.Owner_Id = db.Cats.FirstOrDefault(x => x.MainLang_Id == tmp).Id;
                        }
                    }
                    #region CAT LINK
                    if (cat.PostType.Active == true && cat.PostType.AsPost == true && cat.PostType.Has_Cat == true)
                    {
                        //edit by luan 5/12/2014
                        url = "/" + cat.Lang + "/" + catslug;

                        //old
                        /* if (cat.Level == 3)
                         {
                             var cat2 = db.Cats.Find(cat.Owner_Id);
                             var catslug2 = db.Slugs.FirstOrDefault(x => x.Cat == cat2.Id).Slug_Full;
                             var cat1 = db.Cats.Find(cat2.Owner_Id);
                             var catslug1 = db.Slugs.FirstOrDefault(x => x.Cat == cat1.Id).Slug_Full;

                             url = "/" + cat.Lang + "/" + posttype + "/" + catslug1 + "/" + catslug2 + "/" + catslug;
                         }
                         else if (cat.Level == 2)
                         {
                             var cat1 = db.Cats.Find(cat.Owner_Id);
                             var catslug1 = db.Slugs.FirstOrDefault(x => x.Cat == cat1.Id).Slug_Full;
                             url = "/" + cat.Lang + "/" + posttype + "/" + catslug1 + "/" + catslug;
                         }
                         else if (cat.Level == 1)
                         {
                             url = "/" + cat.Lang + "/" + posttype + "/" + catslug;
                         }*/
                    }
                    #endregion
                }

                #region SPECIAL LINK (contact, search, home)
                else if (type == "contact")
                {
                    url = "/" + culture + "/lien-he";
                }
                else if (type == "search")
                {
                    url = "/" + culture + "/search";
                }
                else if (type == "home")
                {
                    url = "/" + culture;
                }
                #endregion

                return url;
            }
            catch
            {
                return "";
            }
        }

        public ActionResult LoadURL2(string culture, string type, int id = 0)
        {
            try
            {
                var url = "#";
                if (type == "posttype")
                {
                    var posttype = db.Slugs.FirstOrDefault(x => x.PostType == id && x.Lang == culture).Slug_Full;
                    url = "/" + culture + "/" + posttype;
                }
                else if (type == "post")
                {
                    var post = db.Posts.Find(id);
                    var postslug = db.Slugs.FirstOrDefault(x => x.Post == post.Id).Slug_Full;
                    // Luu y slug culture cua Post va Cat la khac nhau
                    // NEU WEBSITE 1 NGON NGU THI BO CAC PHAN CULTURE VA LANG DI (LUU Y LA VAN GIU LAI PHAN RESOURCE

                    #region POST LINK
                    if (post != null)
                    {
                        if (post.PostType.AsPost == true && post.PostType.Active == true)
                        {
                            //edit by luan
                            url = "/" + post.Lang + "/" + postslug;

                            //old
                            if (post.PostType.ShowType == true)
                            {
                                var posttype = db.Slugs.FirstOrDefault(x => x.PostType == post.PostType.Id && x.Lang == culture).Slug_Full;
                                url = "/" + post.Lang + "/" + posttype + "/" + postslug;
                            }

                        }
                    }
                    #endregion
                }

                return Redirect(url);
            }
            catch
            {
                return RedirectToAction("index", "home");
            }
        }
        #endregion

        #region Attribute
        //
        // GET: /Common/
        public string LoadAttribute(string code, int id)
        {
            try
            {
                Post_PostAttribute attribute = db.Post_PostAttributes.FirstOrDefault(x => x.Id_Post == id && x.PostAttribute.Code == code);
                attribute.Value = System.Web.HttpUtility.HtmlDecode(attribute.Value);
                return attribute.Value;
            }
            catch
            {
                return string.Empty;
            }
        }
        #endregion

        #region Breadcrumb
        public ActionResult Breadcrumb(string breadcrumb)
        {
            ViewBag.BreadCrumb = breadcrumb;

PixelCMS.Web/Views/Content/Cat.cshtml
@model PagedList.IPagedList<PixelCMS.Core.Models.Post>
@using PagedList.Mvc;
@{
    if(ViewBag.CatTitle != null){
        ViewBag.Title = ViewBag.CatTitle;
    }else{
        ViewBag.Title = ViewBag.TypeName;
    }
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Metas {
    @if (ViewBag.CatKey != null)
    {
        <meta name="keywords" content="@ViewBag.CatKey" />
    }
    else
    {
        <meta name="keywords" content="@Html.Action("LoadOption", "Common", new { code = "meta-keywords" })" />
    }
    @if (ViewBag.CatDescription != null)
    {
        <meta name="description" content ="@ViewBag.CatDescription" />
    }
    else
    {
        <meta name="description" content="@Html.Action("LoadOption", "Common", new { code = "meta-description" })" />
    }
    @if (ViewBag.CatDescription != null)
    {
        @ViewBag.CatHead
    }
    else
    {
        @Html.Action("LoadOption", "Common", new { code = "meta-htmlheader" })
    }
}

@if (User.IsInRole("tkmadmin") || User.IsInRole("rootadmin")){
    @section adminpanel{
     @Html.Action("AdminPanel","Common")
    }
}

<!-- Page Subtitle -->
<div id="subtitle">
    <div class="container">
        <div class="sixteen columns">
            <h1>
                @ViewBag.CategoryCurrent
            </h1>
        </div>
    </div>
</div>

<div class="container">
    <div class="sixteen columns">
        @Html.Action("Breadcrumb", "Common", new { type = "cat", id = ViewBag.CatId })
    </div>
    <!-- Posts Container-->
    <div class="eleven columns">

        @if (Model.FirstOrDefault() != null)
        {
            <div id="blog_post_container">
                @foreach (var item in Model)
                { 
                    <!-- Post-->
                    <div class="post">
                        <h2><a href="@Html.Action("LoadURL", "Common", new { type = "post", id = item.Id })">@item.Title</a></h2>
                        <div class="post-meta">@item.Date_Create<span class="sep">|</span>@Resources.common_by @item.User_Create</div>
                        @if (item.PostType.Has_Thumb == true)
                        {
                            <div class="post-thumb"><a href="@item.Thumb" rel="prettyPhoto" title="@item.Title.">
                                <img src="@item.Thumb" alt=""/><div class="overlay zoom"></div>
                            </a></div>
                        }
                        <div class="post-content">
                            <p>@item.Description</p>
                        </div>
                        <a class="post-entry" href="@Html.Action("LoadURL", "Common", new { type = "post", id = item.Id })">@Resources.common_readmore</a>
                    </div>
                    <!-- End Post-->
                }
            </div>
            <!-- End Posts Container-->
				
            <div>
                <br />
                @Html.PagedListPager(Model, page => Url.Action("Cat", new { page }))
                @Resources.common_viewingpage @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) (@Resources.common_in @Model.PageCount @Resources.common_page)
                <br />
            </div>
        }
        else
        {
            <div class="alert light_pink">
                @Resources.common_nopost
            </div>
        }
    </div>

    <!-- Widget Container-->
    <div class="five columns">
        <div id="blog_widget_container">

            <div class="widget">
                <div class="widget-title">
                    <h3>Categories</h3>
                </div>
                <div class="widget-archives">
                    <ul>
                        <li><a href="#">Web Design</a></li>
                        <li><a href="#">Graphic Design</a></li>
                        <li><a href="#">CMS Development</a></li>
                        <li><a href="#">Creative</a></li>
                        <li><a href="#">Business</a></li>
                    </ul>
                </div>
            </div>

        </div>
    </div>
    <!-- End Widget Container-->

</div>

PixelCMS.Web/Views/Content/CompareList.cshtml
@model IEnumerable<Post>
@using PixelCMS.Core.Models;
@{
    pixelcmsEntities db = new pixelcmsEntities();
    var currentlang = PixelCMS.Helpers.CultureHelper.GetCurrentNeutralCulture();
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="main-container">
    <div class="page-top-leader omega">
        <div class="container_12 relatived clearfix">
            <h1 class="page-title">Compare list</h1>
            <a href="@Url.Action("ClearCompareList", "Common")">Clear list</a>
        </div>
    </div>
    <div class="container_12 full-container">
        <div class="product-grid omega">
            @foreach (var item in Model)
            {
                <table style="float: left">
                    <tr>
                        <td></td>
                        <td>
                            <a href="@Url.Action("RemoveCompareList", "Common", new { id = item.Id })">Remove</a>
                            <img src="@item.Thumb"/>
                        </td>
                    </tr>
                    <tr>
                        <td>Tên:</td>
                        <td>@item.Title</td>
                    </tr>
                    <tr>
                        <td>Giá:</td>
                        <td>@item.Price</td>
                    </tr>
                    @if (item.Product != null && item.Product.Product_ProductAttribute.FirstOrDefault() != null)
                    {
                        var proGroup = db.ProductAttributeGroups;
                        foreach (var group in proGroup)
                        {
                        <tr>
                            <th>
                                @group.Name
                            </th>
                        </tr>
                            foreach (var att in group.ProductAttributes)
                            {
                                var value = att.Product_ProductAttribute.FirstOrDefault(x => x.Product_Id == item.Product_Id);
                        <tr>
                            <td>@att.Name</td>
                            @if (value != null)
                            {
                                <td>
                                    @value.Value
                                </td>
                            }
                        </tr>
                            }
                        }
                    }

                </table> 
            }
        </div>
    </div>
</div>

PixelCMS.Web/Views/Content/Contact.Mobile.cshtml
@model PixelCMS.Core.Models.Email

@{
    ViewBag.Title = Resources.contact + "mo";
    Layout = "~/Views/Shared/Layout.Mobile.cshtml";
}

<section class="main">
    <div class="title-head"><i class="fa fa-arrow-circle-right"></i>Thông tin liên hệ</div>
    <div class="frm-contact wrap-page">
        <div class="form-group">
            <div id="status" class="status alert alert-success" style="display: none"></div>
            @using (Ajax.BeginForm("ContactForm", "Common"
                                       , new AjaxOptions
                                       {
                                           HttpMethod = "POST",
                                           InsertionMode = InsertionMode.Replace,
                                           OnBegin = "onLoginBegin",
                                           UpdateTargetId = "target",
                                           //OnFailure = "ShowError()",
                                           OnSuccess = "ShowSuccessContact"
                                       }
                    ))
            {
                <div class="frow">
                    @Html.TextBoxFor(model => model.Username, new { placeholder = "Name", @class = "form-control", minlength = "2", maxlength = "142", required = true })
                    @* <input type="text" placeholder="Họ tên">*@
                </div>
                <div class="frow">
                    @Html.TextBoxFor(model => model.Email1, new { placeholder = "Email", @class = "form-control", minlength = "2", maxlength = "142", required = true, type = "email" })
                </div>  
                <div class="frow">
                    @Html.TextBoxFor(model => model.Subject, new { placeholder = "Subject", @class = "form-control", minlength = "2", maxlength = "142", required = true })
                </div> 
                <div class="frow">
                    @Html.TextBoxFor(model => model.Phone, new { placeholder = "Phone", @class = "form-control", minlength = "2", maxlength = "142", required = true })
                </div>   	
                <div class="frow">
                    @Html.TextAreaFor(model => model.Text, new { rows = "8", @class = "form-control", placeholder = "Content", minlength = "5", required = true })
                </div> 
           	<div class="frow fcenter"><button type="submit">Gửi</button></div>
            
            }

        </div>
    </div>
</section>


<div id="loading">
    <img src="~/Content/loading.gif" />
</div>
<!-- Contact / End
================================================== -->
<style>
    .style-button
    {
        background-color: #428bca;
        color: white;
    }

    .contactform input, textarea
    {
        float: left;
        clear: both;
        margin-top: 12px;
        width: 100%;
    }
</style>

<style>
    .alert
    {
        padding: 15px;
        margin-bottom: 20px;
        border: 1px solid transparent;
        border-radius: 4px;
    }

    .alert-success
    {
        background-color: #dff0d8;
        border-color: #d6e9c6;
        color: #3c763d;
    }

    .alert-danger
    {
        background-color: #f2dede;
        border-color: #ebccd1;
        color: #a94442;
    }

    #loading
    {
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        width: 100px;
        background: #FFF;
        padding: 10px;
        box-shadow: 1px 1px 4px rgba(0,0,0,0.4);
    }
</style>

<script>

    function onLoginBegin() {
        $('#contact-submit-button').hide();
        $("#loading").fadeIn();
    }

    function ShowSuccessContact(data) {
        //chat..........................
        var chatHub = $.connection.chatHub;
        // Start Hub
        $.connection.hub.start().done(function () {
            chatHub.server.message("contact");
        });
        if (data.succsess == true) {
            $("#status").removeClass();
            $("#status").addClass("alert alert-success").css("color", "blue").show();
            $("#status").html("@Resources.contact_form_success").fadeOut(5000);
            $("#loading").fadeOut();
            $("#form0 input[type!=submit],textarea").val('');
            /*$("#contact-submit-button").fadeIn();*/
        } else {
            $("#status").removeClass();
            $("#status").addClass("alert alert-danger").css("color", "red");;
            $("#status").html("@Resources.contact_form_fail");
            $("#loading").fadeOut();
        }

    }
</script>

PixelCMS.Web/Views/Content/CustomerDetail.cshtml
@model PixelCMS.Core.Models.Post
@using PixelCMS.Core.Models;
@{
    pixelcmsEntities db = new pixelcmsEntities();
    if (Model.Meta_Title != null)
    {
        ViewBag.Title = Model.Meta_Title;
    }
    else
    {
        ViewBag.Title = Model.Title;
    }
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Metas {
    @if (Model.Meta_key != null)
    {
    <meta name="keywords" content="@Model.Meta_key" />
    }
    @if (Model.Meta_Description != null)
    {
    <meta name="description" content ="@Model.Meta_Description" />
    }
    @if (Model.Html_Head != null)
    {
    @Html.Raw(Model.Html_Head)
    }
}

@if (User.IsInRole("tkmadmin") || User.IsInRole("rootadmin")){
    @section adminpanel{
     @Html.Action("AdminPanel","Common",new{postid=Model.Id,posttype=Model.PostType.Name})
    }
}

@{
    var imagelink = db.MediaFiles.Where(x => x.Post.Id == Model.Id).OrderBy(o=>o.Order).ToList();    
}

        <!-- Page title -->
        <div id="page-title">
            <div class="container">
                <div class="sixteen columns alpha omega">
                    <h1>@Model.Title</h1>
                </div>
            </div>
        </div>
        <!-- /Page title -->
        
        <div id="breadcrumbs">
            <div class="container">
                <div class="sixteen columns alpha omega">
		@Html.Action("Breadcrumb","Common",new{breadcrumb = ViewBag.BreadCrumb})
                </div>
            </div>
        </div>


   <!-- Content -->
    <section id="content">
        <div class="container">
            <div class="nine columns">
            <div class="project-image portfolio"> 
                @if(imagelink.FirstOrDefault() != null){
				<div class="flexslider">
                  <ul class="slides">
                    @foreach (var image in imagelink) { 
                        <li><a href="@image.URL" rel="prettyPhoto[portfolio]"><img src="@image.URL" alt="" /></a></li>    
                        }

				</ul>
                </div> 
                }
                else{
                    <span>@Resources.common_nopic</span>
                }
                </div>
            </div>
            
            <div class="seven columns">
                <div class="project-details">
				<h2>@Model.Title</h2>
				
				<div class="clear"></div>
				<hr />

				<ul>
					<li><span>@Resources.common_date:</span>@Html.Action("LoadAttribute","Common",new{id=Model.Id,code="project-date"})</li>
					<li><span>@Resources.common_customer:</span>@Html.Action("LoadAttribute","Common",new{id=Model.Id,code="project-customer"})</li>
					<li><span>@Resources.common_description:</span>@Model.Description</li>
				</ul>
                    <a class="btn-image" href="@Html.Action("LoadAttribute","Common",new{id=Model.Id,code="project-link"})" target="_blank">@Resources.project_visitwebsite</a>
			    </div>

                <article class="project-description">
				@Html.Raw(Model.Content)
			    </article>

            </div>

        </div>
    </section>


@section css{
    <link rel="stylesheet" href="~/Theme/css/flexslider.css" type="text/css">
    <link rel="stylesheet" href="~/Theme/css/prettyPhoto.css" type="text/css" media="screen" title="prettyPhoto main stylesheet" charset="utf-8" />
    }

@section scripts{
    @Scripts.Render("~/Theme/js/prettyPhoto")
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function () {
            $("area[rel^='prettyPhoto']").prettyPhoto();

            $(".portfolio:first a[rel^='prettyPhoto']").prettyPhoto({ animation_speed: 'fast', theme: 'pp_default', slideshow: 4000, opacity: 0.50, deeplinking: false, overlay_gallery: false, autoplay_slideshow: false });

        });
	</script>

    <!-- FlexSlider -->    
    <script src="~/Theme/js/jquery.flexslider.js"></script>
	<script type="text/javascript">
            $(function(){
              SyntaxHighlighter.all();
            });
            $(window).load(function(){
              $('.flexslider').flexslider({
                animation: "fade",
                start: function(slider){
                  $('body').removeClass('loading');
                }
              });
            });
	</script>
    <!-- /FlexSlider -->
    }

PixelCMS.Web/Views/Content/CustomerList.cshtml
@model PagedList.IPagedList<PixelCMS.Core.Models.Post>
@using PagedList.Mvc;
@using PixelCMS.Core.Models;
@{
    pixelcmsEntities db = new pixelcmsEntities();
    var currentlang = PixelCMS.Helpers.CultureHelper.GetCurrentNeutralCulture();
    
    if(ViewBag.CatTitle != null){
        ViewBag.Title = ViewBag.CatTitle;
    }else{
        //ViewBag.Title = ViewBag.CategoryCurrent;
        ViewBag.Title = ViewBag.TypeName;
    }
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Metas {
    @if (ViewBag.CatKey != null)
    {
        <meta name="keywords" content="@ViewBag.CatKey" />
    }
    @if (ViewBag.CatDescription != null)
    {
        <meta name="description" content ="@ViewBag.CatDescription" />
    }
    @if (ViewBag.CatHead != null)
    {
        @Html.Raw(ViewBag.CatHead)
    }
}

@if (User.IsInRole("tkmadmin") || User.IsInRole("rootadmin")){
    @section adminpanel{
     @Html.Action("AdminPanel","Common")
    }
}

        <!-- Page title -->
        <div id="page-title">
            <div class="container">
                <div class="sixteen columns alpha omega">
                    <h1>@ViewBag.TypeName</h1>
                </div>
            </div>
        </div>
        <!-- /Page title -->
        
        <div id="breadcrumbs">
            <div class="container">
                <div class="sixteen columns alpha omega">
		@Html.Action("Breadcrumb","Common",new{breadcrumb = ViewBag.BreadCrumb})
                </div>
            </div>
        </div>



<section id="content">
    <div class="container">
        <div class="sixteen columns">
		
			<!-- Isotope Filter -->
			@Html.Action("CustomerCatList","Widget")
			<!-- Isotope Filter / End -->
			
		</div>


        <div class="sixteen columns">
            <div id="projects4">
            <ul class="portfolio group"> 

                @foreach (var item in Model)
                {
                    /* Parallel Lang */
                    if (item.Lang != currentlang)
                    {
                        var itemlang = db.Posts.FirstOrDefault(x => x.Lang == currentlang && x.MainLang_Id == item.Id);
                        item.Id = itemlang.Id;
                        item.Title = itemlang.Title;
                        item.Description = itemlang.Description;
                        item.Content = itemlang.Content;
                    }
                    /* End Parallel Lang */
                    var imagelink = "";
                    var catslug = "";
                    if (db.MediaFiles.FirstOrDefault(x => x.Post.Id == item.Id) != null)
                    {
                        imagelink = db.MediaFiles.Where(x => x.Post.Id == item.Id).OrderBy(o => o.Order).FirstOrDefault().URL;
                    }
                    if (item.Cats.FirstOrDefault() != null)
                    {
                        catslug = item.Cats.FirstOrDefault().Slugs.FirstOrDefault().Slug_Full;
                    }
                    
                <li class="item" data-id="id-@item.Id" data-type="@catslug">
                    
                    <div class="view overlay">
                        <img src="@item.Thumb" alt="title here" />
                        
                        <a href="@Html.Action("LoadURL","Common",new{type="post",id=item.Id})" >
                            <div class="mask">
                                <h3>@item.Title</h3>                          
                            </div>
                        </a>
                        
                        <a href="@imagelink" rel="prettyPhoto[portfolio]"><div class="info"><img src="~/Theme/images/zoom.png" /></div></a>
                        
                    </div>
                      
                </li>
        }

            </ul>
                </div>
        </div>


    </div>
</section>

@section css{
    <link rel="stylesheet" type="text/css" href="~/Theme/css/prettyPhoto.css"/>
    }

@section scripts{
    @Scripts.Render("~/Theme/js/prettyPhoto")
    }

PixelCMS.Web/Views/Content/ProductList.Mobile.cshtml
@model PagedList.IPagedList<PixelCMS.Core.Models.Post>
@using PagedList.Mvc;
@using PixelCMS.Core.Models;
@{
    pixelcmsEntities db = new pixelcmsEntities();
    var currentlang = PixelCMS.Helpers.CultureHelper.GetCurrentNeutralCulture();

    var count = Request.Url.Segments.Count();
    var slug = Request.Url.Segments[count - 1];
    var fullslug = db.Slugs.FirstOrDefault(x => x.Slug_Full == slug);

    if (ViewBag.CatTitle != null)
    {
        ViewBag.Title = ViewBag.CatTitle;
    }
    else
    {
        //ViewBag.Title = ViewBag.CategoryCurrent;
        ViewBag.Title = ViewBag.TypeName;
    }

    Layout = "~/Views/Shared/Layout.Mobile.cshtml";
}

@section Metas {
    @if (ViewBag.CatKey != null)
    {
        <meta name="keywords" content="@ViewBag.CatKey" />
    }
    @if (ViewBag.CatDescription != null)
    {
        <meta name="description" content ="@ViewBag.CatDescription" />
    }
    @if (ViewBag.CatHead != null)
    {
        @Html.Raw(ViewBag.CatHead)
    }
}
<link href="~/Content/PagedList.css" rel="stylesheet" />
<section class="main">
	<div class="title-head"><i class="fa fa-arrow-circle-right"></i> @ViewBag.TypeName</div>
	<div class="product-list">    	
        <div class="row">
                   <div id="update1">
                        @Html.Action("ProductGridMobile", "Common")
                    </div>
        </div>
	</div><!-- End product-list -->
</section>
 